# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml/

authors = ["komuro@fastly.com"]
description = "GRIP demo of WebSocket-over-HTTP on Fastly Fanout"
language = "javascript"
manifest_version = 3
name = "fastly-websocket"

[local_server]

  [local_server.backends]

    [local_server.backends.publisher]
      override_host = "localhost:5561"
      url = "http://localhost:5561/"

  [local_server.secret_stores]

    [[local_server.secret_stores.fastly_websocket_config]]
      data = "http://localhost:5561/"
      key = "GRIP_URL"

[setup]

  [setup.secret_stores]

    [setup.secret_stores.fastly_websocket_config]
      description = "Configuration data for WebSocket-over-HTTP service"

      [setup.secret_stores.fastly_websocket_config.entries]

        [setup.secret_stores.fastly_websocket_config.entries.GRIP_URL]
          description = "GRIP_URL"

        [setup.secret_stores.fastly_websocket_config.entries.GRIP_VERIFY_KEY]
          description = "GRIP_VERIFY_KEY"

[scripts]
  build = "npm run build"
  post_init = "npm install"
